blank_issues_enabled: false
contact_links:
  - name: Have an idea you'd like to discuss with other members?
    url: https://github.com/orgs/django-commons/discussions
    about: Please ask and answer questions here.
  - name: Request to be an Admin
    url: https://forms.gle/ZDUtLcvmWUAES2RN8
    about: Interested in becoming a Django Commons admin? Fill out our interest form.
