name: "Apply org repositories changes"

on:
  push:
    branches:
      - main
    paths:
      - 'terraform/repositories.tfvars'
      - 'terraform/repositories/*.tf'
      - '.github/workflows/repos-apply.yml'
      - '.github/workflows/repos-plan.yml'

concurrency:
  group: terraform-actions-repos

jobs:
  repos-apply-changes:
    name: "Apply org-repositories changes"
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: write
    timeout-minutes: 10
    steps:
      - name: Checkout code
        uses: actions/checkout@v6  # zizmor: ignore[unpinned-uses]
        with:
          persist-credentials: false
      - name: terraform apply
        uses: dflook/terraform-apply@8f47d0ad9f3cb9e50fd6b3595c0cb98f00c518df # v2.2.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TERRAFORM_ACTIONS_GITHUB_TOKEN: ${{ secrets.TERRAFORM_MANAGEMENT_GITHUB_TOKEN }}
        with:
          auto_approve: true
          path: "terraform/repositories"
          label: 'repositories'
          variables: |
            github_token = "${{ secrets.TERRAFORM_MANAGEMENT_GITHUB_TOKEN }}"
          var_file: |
            terraform/repositories.tfvars

      - name: Commit changes
        if: ${{ always() }}
        uses: devops-infra/action-commit-push@8a2d9d73c3f506468129be2e4409e60dbed70357 # v1.0.3
        with:
          github_token: ${{ secrets.TERRAFORM_MANAGEMENT_GITHUB_TOKEN }}
          commit_prefix: "[AUTO]"
          commit_message: "Repositories state changes after apply"
          force: false
